/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.blz.censusanalyzer.tester;

import org.junit.Test;

import com.blz.censusanalyzer.controller.CensusAnalyser;
import com.blz.censusanalyzer.controller.CensusAnalyserException;

import junit.framework.Assert;

@SuppressWarnings("deprecation")
public class CensusAnalyserTest {
	private static String CORRECT_CSV_FILE_PATH = "E:\\Eclipse-Workspace-java-developer\\CensusAnalyzerAssignment\\src\\test\\resources\\IndianStateCensusData.csv";
	@Test
	public void givenIndianCensusCSVFile_ShouldReturnCorrectNumberOfRecordTest() {
		CensusAnalyser censusAnalyzerObj=new CensusAnalyser();
		int numOfEntries=censusAnalyzerObj.loadIndiaCensusData(CORRECT_CSV_FILE_PATH);
		Assert.assertEquals(29, numOfEntries);
	}
}
